apiVersion: apps/v1
kind: Deployment
metadata:
  name: harness-demo
  namespace: harness-demo
  labels:
    app: harness-demo
    version: stable
spec:
  replicas: 2
  selector:
    matchLabels:
      app: harness-demo
  template:
    metadata:
      labels:
        app: harness-demo
        version: stable
    spec:
      containers:
        - name: harness-demo
          image: raphaelokere/harness-demo:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "stable"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
