apiVersion: v1
kind: Service
metadata:
  name: harness-demo
  namespace: harness-demo
  labels:
    app: harness-demo
spec:
  selector:
    app: harness-demo
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
